// Auto-generated by: supabase gen types typescript --linked > src/types/database.ts
// Run this command after each migration to keep types in sync.
// Do not hand-edit this file.

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          role: 'admin' | 'player'
          name_slug: string
          gender: 'M' | 'F' | null
          level: number | null
          created_at: string
        }
        Insert: {
          id: string
          role?: 'admin' | 'player'
          name_slug: string
          gender?: 'M' | 'F' | null
          level?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          role?: 'admin' | 'player'
          name_slug?: string
          gender?: 'M' | 'F' | null
          level?: number | null
          created_at?: string
        }
        Relationships: []
      }
      sessions: {
        Row: {
          id: string
          name: string
          date: string
          status: 'setup' | 'registration_open' | 'registration_closed' | 'schedule_locked' | 'in_progress' | 'complete'
          created_by: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          date: string
          status?: 'setup' | 'registration_open' | 'registration_closed' | 'schedule_locked' | 'in_progress' | 'complete'
          created_by: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          date?: string
          status?: 'setup' | 'registration_open' | 'registration_closed' | 'schedule_locked' | 'in_progress' | 'complete'
          created_by?: string
          created_at?: string
        }
        Relationships: []
      }
      session_invitations: {
        Row: {
          id: string
          session_id: string
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          session_id: string
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          session_id?: string
          is_active?: boolean
          created_at?: string
        }
        Relationships: []
      }
      session_registrations: {
        Row: {
          id: string
          session_id: string
          player_id: string
          registered_at: string
        }
        Insert: {
          id?: string
          session_id: string
          player_id: string
          registered_at?: string
        }
        Update: {
          id?: string
          session_id?: string
          player_id?: string
          registered_at?: string
        }
        Relationships: []
      }
      matches: {
        Row: {
          id: string
          session_id: string
          queue_position: number
          team1_player1_id: string
          team1_player2_id: string
          team2_player1_id: string
          team2_player2_id: string
          status: 'queued' | 'playing' | 'complete'
          court_number: number | null
          created_at: string
        }
        Insert: {
          id?: string
          session_id: string
          queue_position: number
          team1_player1_id: string
          team1_player2_id: string
          team2_player1_id: string
          team2_player2_id: string
          status?: 'queued' | 'playing' | 'complete'
          court_number?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          session_id?: string
          queue_position?: number
          team1_player1_id?: string
          team1_player2_id?: string
          team2_player1_id?: string
          team2_player2_id?: string
          status?: 'queued' | 'playing' | 'complete'
          court_number?: number | null
          created_at?: string
        }
        Relationships: []
      }
      match_results: {
        Row: {
          id: string
          match_id: string
          winning_pair_index: 1 | 2
          completed_at: string
        }
        Insert: {
          id?: string
          match_id: string
          winning_pair_index: 1 | 2
          completed_at?: string
        }
        Update: {
          id?: string
          match_id?: string
          winning_pair_index?: 1 | 2
          completed_at?: string
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      session_status: 'setup' | 'registration_open' | 'registration_closed' | 'schedule_locked' | 'in_progress' | 'complete'
      match_status: 'queued' | 'playing' | 'complete'
    }
  }
}
